hard coding - delibrately writing lines of code by yourself without any assistance

In [3]:
list = [1,2,3,4,5]
list[2]

3

In [2]:
list = [[1,2,3,4,5],[1,2,3,4,5]]
type(list)

list

In [4]:
import numpy as np
list = np.array([[1,2,3,4,5],[1,2,3,4,5]])

In [5]:
print(list)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [6]:

list = np.array([[1,2],[4,5],[1,2],[4,5]])
list

array([[1, 2],
       [4, 5],
       [1, 2],
       [4, 5]])

In [7]:
array = np.array([[1,2,3],[1,2,3],[1,2,3]])
array

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [11]:
# operatios in array
arr1 = np.array([[1,2,3],[1,2,3]])
arr2 = np.array([[2,4,5],[3,4,5]])
arr3 = arr1+arr2
arr4 = arr1-arr2
arr5 = arr1*arr2
print(arr3,arr4,arr5)

[[3 6 8]
 [4 6 8]] [[-1 -2 -2]
 [-2 -2 -2]] [[ 2  8 15]
 [ 3  8 15]]


In [ ]:
#properties of array
arr1.shape

(2, 3)

In [13]:
arr1.all

<function ndarray.all>

In [15]:
arr1.sum(axis=0)

array([2, 4, 6])

In [17]:
arr1.sum(axis=1)

array([6, 6])

In [19]:
arr1.ndim

2

In [20]:
# slicing in array
arr1[0:2,0:2]

array([[1, 2],
       [1, 2]])

In [3]:
import pandas as pd

In [4]:
#vector
data = [1,2,3,4,4,5,4,]
series = pd.Series(data)
series

0    1
1    2
2    3
3    4
4    4
5    5
6    4
dtype: int64

In [5]:
data = {"a": [1,2,3],
        "b":[4,6,8],
        "c":[5,6,7]
        }
        

df = pd.DataFrame(data)
df

a  b  c
0  1  4  5
1  2  6  6
2  3  8  7

In [6]:
df.to_csv('my_data.csv', index=False)

In [7]:

df = pd.read_csv('my_data.csv')

In [8]:
print(df)

   a  b  c
0  1  4  5
1  2  6  6
2  3  8  7
